nav:
  # 導航欄 Logo 圖片
  logo: /statics/avatar.png
  # 是否顯示標題
  display_title: true
  # 是否固定導航欄
  fixed: true

#highlight
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: 日常
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

menu:
  主页: / || fas fa-home
  博文 || fa fa-graduation-cap:
    分类: /categories/ || fa fa-archive
    标签: /tags/ || fa fa-tags
    归档: /archives/ || fa fa-folder-open
  生活 || fas fa-list:
    说说: /shuoshuo/ || fa-solid fa-door-open
    相册: /photos/ || fa fa-camera-retro
  友链: /links/ || fa-solid fa-users

#联系作者
social:
  fab fa-github: https://github.com/Cn-0kr || Github || "#hdhfbb"
  fas fa-envelope: mailto:xxxxxx@gmail.com || Email || "#000000"

highlight_theme: mac  #  darker / pale night / light / ocean / mac / mac light / false 代码主题
highlight_copy: true # 复制按钮
highlight_lang: false # 是否显示代码语言
highlight_shrink: false # true: 代码块默认不展开 / false: 代码块默认展开 | none: 展开并隐藏折叠按钮
highlight_height_limit: 230 # unit: px
code_word_wrap: false #代码自动换行，关闭滚动条

code_blocks:
  # Code block theme: darker / pale night / light / ocean / false
  theme: light
  macStyle: false
  # Code block height limit (unit: px)
  height_limit: false
  word_wrap: false

#头像
avatar:
  img: /statics/avatar.png
  effect: false # 頭像會一直轉圈

#图片初始化
index_img: /statics/landscape001.jpg
footer_img: /statics/landscape002.jpg
default_top_img: /statics/landscape001.jpg
tag_img: /statics/tags.jpg
category_img: /statics/categories.jpg
#封面
cover:
  default_cover:
    - /statics/landscape002.jpg
    - /statics/landscape003.jpg
    - /statics/landscape004.jpg
    - /statics/landscape001.jpg

#主页副标题
# 主頁subtitle
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # Customize typed.js
  # https://github.com/mattboldt/typed.js/#customization
  typed_option:
  # source 調用第三方服務
  # false 關閉調用
  # 1  調用一言網的一句話（簡體） https://hitokoto.cn/
  # 2  調用一句網（簡體） http://yijuzhan.com/
  # 3  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  source: false
  # 如果關閉打字效果，subtitle 只會顯示 sub 的第一行文字
  sub:
    - 今日事&#44;今日毕
    - Never put off till tomorrow what you can do today

#主页布局
index_layout: 3

#文章节选
# Display the article introduction on homepage
# 1: description
# 2: both (if the description exists, it will show description, or show the auto_excerpt)
# 3: auto_excerpt (default)
# false: do not show the article introduction
index_post_content:
  method: 2
  # If you set method to 2 or 3, the length need to config
  length: 500

#meta提示
post_meta:
  # Home Page
  page:
    # Choose: created / updated / both
    date_type: created
    # Choose: date / relative
    date_format: date
    categories: true
    tags: true
    label: true
  post:
    # Choose: left / center
    position: left
    # Choose: created / updated / both
    date_type: both
    # Choose: date / relative
    date_format: date
    categories: true
    tags: true
    label: true

#article content 文章目录
toc:
  post: true
  page: false
  number: true
  expand: false
  # Only for post
  style_simple: false
  scroll_percent: true

#相关文章推荐
related_post:
  enable: true
  limit: 3 # 顯示推薦文章數目
  date_type: created # or created or updated 文章日期顯示創建日或者更新日

# 页面锚点
anchor:
  # when you scroll, the URL will update according to header id.
  auto_update: true
  # Click the headline to scroll and update the anchor
  click_to_scroll: true

#图片描述显示
photofigcaption: true

# Giscus评论区
# https://giscus.app/
comments:
  # Up to 2 comments system, the first will be shown as default
  # Choose: Valine/Disqus/Twikoo/Artalk/Waline/Giscus/Remark42/Gitalk
  use: Giscus
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in post's top_img
  card_post_count: true # Display comment count in Home Page
# Giscus
giscus:
  repo: Cn-0kr/commentsInGiscus
  repo_id: R_kgDONInfCQ
  category_id: DIC_kwDONInfCc4Cj3Xz
  theme:
    light: light
    dark: dark
  option:

#打赏赞助
reward:
  enable: true
  text:
  QR_code:
    - img: /img/wechat.jpg
      link:
      text: 微信
    - img: /img/alipay.jpg
      link:
      text: 支付寶

#chat deprecated
chat:
  # Choose: chatra/tidio/crisp
  # Leave it empty if you don't need chat
  use:
  # Chat Button [recommend]
  # It will create a button in the bottom right corner of website, and hide the origin button
  rightside_button: false
  # The origin chat button is displayed when scrolling up, and the button is hidden when scrolling down
  button_hide_show: false

#底部栏tabber
footer:
  owner:
    enable: true
    since: 2024
    custom_text: 沪ICP备2024053501号-1       © 2024 0kr. All rights reserved.

copy:
  enable: true
  # Add the copyright information after copied content
  copyright:
    enable: true
    limit_count: 300

#美化部分
theme_color:
  enable: true
  main: '#49B1F5'
  paginator: '#00c4b6'
  button_hover: '#FF7242'
  text_selection: '#00c4b6'
  link_color: '#99a9bf'
  meta_color: '#858585'
  hr_color: '#A4D8FA'
  code_foreground: '#F47466'
  code_background: 'rgba(27, 31, 35, .05)'
  toc_color: '#00c4b6'
  blockquote_padding_color: '#49b1f5'
  blockquote_background_color: '#49b1f5'
  scrollbar_color: '#49b1f5'
  meta_theme_color_light: 'ffffff'
  meta_theme_color_dark: '#0d0d0d'

# Add a mask to the header and footer
mask:
  header: true
  footer: true

# 加載動畫 Loading Animation
preloader:
  enable: false
  # source
  # 1. fullpage-loading
  # 2. pace (progress bar)
  source: 2
  # pace theme (see https://codebyzach.github.io/pace/)
  pace_css_url: /statics/progressBar.gif

# Typewriter Effect (打字效果)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (冒光特效)
  shake: true #  open shake (抖動特效)
  mobile: false
canvas_ribbon:
  enable: true
  # The size of ribbon
  size: 150
  # The opacity of ribbon (0 ~ 1)
  alpha: 0.6
  zIndex: -1
  click_to_change: true
  mobile: false
# Choose: fancybox / medium_zoom
# https://fancyapps.com/fancybox/
# Leave it empty if you don't need lightbox
#查看放大后的图片
lightbox: medium_zoom
# 圖片格式 url(http://xxxxxx.com/xxx.jpg)
# 顏色（HEX值/RGB值/顔色單詞/漸變色)
# 留空 不顯示背景
# Aside Widget
aside:
  enable: true
  hide: false
  # Show the button to hide the aside in bottom right button
  button: true
  mobile: true
  # Position: left / right
  position: right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow
      link: https://github.com/Cn-0kr
  card_announcement:
    enable: true
    content: Welcome to my Blog!! <br> --Initialized in 2024.11
  card_recent_post:
    enable: true
    # If set 0 will show all
    limit: 5
    # Sort: date / updated
    sort: date
    sort_order:
  card_newest_comments:
    enable: false
    sort_order:
    limit: 6
    # Unit: mins, save data to localStorage
    storage: 10
    avatar: true
  card_categories:
    enable: true
    # If set 0 will show all
    limit: 8
    # Choose: none / true / false
    expand: none
    sort_order:
  card_tags:
    enable: true
    # If set 0 will show all
    limit: 40
    color: false
    # Order of tags, random/name/length
    orderby: random
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: 1
    sort_order:
  card_archives:
    enable: true
    # Type: monthly / yearly
    type: monthly
    # Eg: YYYY年MM月
    format: MMMM YYYY
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: -1
    # If set 0 will show all
    limit: 8
    sort_order:
  card_post_series:
    enable: true
    # The title shows the series name
    series_title: true
    # Order by title or date
    orderBy: 'date'
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: -1
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: false
    sort_order:
    # Time difference between publish date and now
    # Formal: Month/Day/Year Time or Year/Month/Day Time
    # Leave it empty if you don't enable this feature
    runtime_date:

  # show scroll percent in scroll-to-top button
  rightside_scroll_percent: true
  # dark mode
  darkmode:
    enable: true
    # dark mode和 light mode切換按鈕
    button: true
    autoChangeMode: false
    # Set the light mode time. The value is between 0 and 24. If not set, the default value is 6 and 18
    start: # 8
    end: # 22

  #字数统计
  # Need to install the hexo-wordcount plugin
  wordcount:
    enable: true
    # Display the word count of the article in post meta
    post_wordcount: true
    # Display the time to read the article in post meta
    min2read: true
    # Display the total word count of the website in aside's webinfo
    total_wordcount: true
